apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-account-svc
  namespace: dev
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /nfs/data/account-svc
    server: 192.168.50.53