kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-account-svc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
  storageClassName: nfs