apiVersion: v1
kind: Service
metadata:
  name: svc-account-svc
  namespace: dev
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8071
    protocol: TCP
    targetPort: 8071
  selector:
    app: deployment-account-svc
