# application.yml
server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: whoami-service

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN:https://80bbf4ae778b525f9fe72e2813cd5246@sentry.io/1271087}
    deploy-env: ${DEPLOY:V2}
  company-service-endpoint: ${COMPANY_SERVICE_ENDPOINT:http://company-service}
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-service}
  intercom-app-id: ${INTERCOM_APP_ID:key}
  intercom-signing-secret: ${INTERCOM_SIGNING_SECRET:value}
