spring:
  datasource:
    url: jdbc:mysql://yzxu.asuscomm.com:3307/staffjoy_account?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8081
staffjoy:
  email-service-endpoint: http://localhost:8088
  company-service-endpoint: http://localhost:8082
  bot-service-endpoint: http://localhost:8087
management:
  endpoints:
    web:
      exposure:
        include: "*"
