# application.yml
server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: bot-service

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN:https://80bbf4ae778b525f9fe72e2813cd5246@sentry.io/1271087}
    deploy-env: ${DEPLOY:V2}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service}
  sms-service-endpoint: ${SMS_SERVICE_ENDPOINT:http://sms-service}
  company-service-endpoint: ${COMPANY_SERVICE_ENDPOINT:http://company-service}
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-service}
  force-email-preference: ${FORCE_EMAIL_PREFERENCE:true}
