COMPANY_DATASOURCE_URL: jdbc:mysql://yzxu.asuscomm.com:3307/staffjoy_company?useUnicode=true&characterEncoding=utf-8
COMPANY_DATASOURCE_USERNAME: root
COMPANY_DATASOURCE_PASSWORD: root

server:
  port: 8082

staffjoy:
  email-service-endpoint: http://localhost:8088
  account-service-endpoint: http://localhost:8081
  bot-service-endpoint: http://localhost:8087

management:
  endpoints:
    web:
      exposure:
        include: "*"
