spring:
  datasource:
    url: jdbc:mysql://yzxu.asuscomm.com:3307/staffjoy_company?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8082

staffjoy:
  email-service-endpoint: http://localhost:8088
  account-service-endpoint: http://localhost:8081
  bot-service-endpoint: http://localhost:8087

management:
  endpoints:
    web:
      exposure:
        include: "*"

SENTRY_DSN: https://80bbf4ae778b525f9fe72e2813cd5246@sentry.io/1271087
