# application.yml

spring:
  profiles:
    active: dev
  application:
    name: www-service

server:
  error:
    whitelabel:
      enabled: false

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN:https://80bbf4ae778b525f9fe72e2813cd5246@sentry.io/1271087}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET:secret}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service}
  company-service-endpoint: ${COMPANY_SERVICE_ENDPOINT:http://company-service}
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-service}
  recaptcha-public: ${RECAPTCHA_PUBLIC}
  recaptcha-private: ${RECAPTCHA_PRIVATE}